* Judith Butler (Critical Thinkers)
** Why Butler?
*** To a greater or lesser extent, all Butler’s books
ask questions about the formation of identity and subjectivity, tracing
the processes by which we become subjects when we assume the
sexed/gendered/‘raced’ identities which are constructed for us (and
to a certain extent by us) within existing power structures. Butler is
engaged in an ongoing interrogation of ‘the subject’ in which she asks
- through what *processes* subjects come into existence,
- by what means they are *constructed*, and
- how those constructions work and fail.

Butler’s ‘subject’ is not an individual, but a linguistic structure in formation.
‘Subjecthood’ is not a given,
and since the subject is always involved in the *endless process of becoming*, it is possible to reassume or repeat subjecthood in different ways. Butler asks in a recent article (WIC:
20):
- Who will be a subject here, and what will count as a life?
- whom do I oppress by constructing a coherent identity for myself and ‘doing’ my identity?
- What happens if our identities ‘fail’, and might such failures provide opportunities for subversive reconstructions of identity?
- Perhaps those reconstructions, as subversive as they may seem, will end up cohering into identity formations which are just as oppressive in their own way.
- How can we tell what is subversive and what merely consolidates power?
- And what degree of choice do we have about how we ‘do’ our identities?
/P. 2/

*** Butler’s works themselves are part of a process or
a becoming which has neither origin nor end; indeed, in which origin
and end are rejected as oppressively, perhaps even violently, linear or
‘teleological’ (i.e. moving towards a specific end or a final outcome).
/P. 3/

*** Within Butler’s dialectical model, knowledge proceeds through opposition and
cancellation, never finally reaching an ‘absolute’ or final certainty, but
only positing ideas that cannot be fixed as ‘truths’. The sciences, which
many people regard as having some sort of authority or claim to ‘truth’,
follow this similar movement through experiment, disagreement and revision.
/P. 3/

*** she regards *resolution* as dangerously *anti-democratic*,
since ideas and theories that present themselves as self-evident ‘truths’
are often *vehicles for ideological assumptions* that oppress certain
groups of people in society, particularly those in the minority or on
the margins.
/P. 3/

*** Butler’s work enters into dialectical
engagement with the categories by which the subject is described
and constituted: including ‘gay’, ‘straight’,
‘bisexual’, ‘transsexual’, ‘black’ and ‘white’, as well as notions such
as ‘truth’, ‘right’ and ‘norm’.
/P. 3/

*** Queer Theory Roots
in the 1980s, when Butler first entered the philosophical theoretical field,
feminist theory began to interrogate (as Butler does) the category of
‘the female subject’ as a stable and self-evident entity. Under the influence
of Foucault, a number of theorists rejected the idea that ‘sex’
was the biologically determined entity it was previously taken to be,
and instead they deployed Foucault’s historical formulations of the
ways in which sex and sexuality are discursively constructed over time
and from culture to culture.
/P. 8/

*** Queer theory thus arose from a coalition (at times an uneasy one)
of feminist, post-structuralist and psychoanalytic theories, which facilitated
and informed the ongoing investigation into the category of
the subject.
/P. 8/

*** Butler’s work has been concerned with
the ongoing analysis and resulting destabilization of the category of ‘the
subject’ (a process she calls ‘a critical genealogy of gender ontologies’).
/P. 7/

*** Sedgwick, a queer theorist whose influential Epistemology of the Closet was
published in 1990, the same year as Gender Trouble, characterizes queer
as indistinguishable, undefinable, mobile. ‘Queer is a continuing moment,
movement, motive – recurrent, eddying, troublant’... queer theory undertakes
an investigation and a deconstruction of these categories, affirming
the indeterminacy and instability of all sexed and gendered identities.
/P. 8/

*** to investigate formulations of
straightness in order to reveal the ‘queerness’ underlying particularly
those identities which aggressively present themselves as straight,
straightforward, singular and stable... Butler draws from Freud in her
theorizations of heterosexuality as a ‘melancholy’ structure of identity
which is based upon a socially imposed primary ‘loss’ or rejection of
homosexual desire.
/P. 9/

*** genealogy is a mode of historical investigation that
does not have ‘the truth’ or even knowledge as its goal. As Butler puts
it, ‘ “Genealogy” is not the history of events, but the enquiry into the
conditions of emergence (Entstehung) of what is called history, a
moment of emergence that is not finally distinguishable from fabrication’
(RBP: 15)... Rather than assuming that
identities are self-evident and fixed as essentialists do, Butler’s work
traces the processes by which identity is constructed within language
and discourse
/P. 10/

*** Butler’s genealogical analyses will focus on how the subject-effect, as
she calls it, comes about, and she will also suggest that there are ways
in which the subject might be ‘effected’ differently.
/P. 10/

*** Butler’s genealogical
critique of the category of the subject dovetails with her notion that
gendered and sexed identities are performative. Here Butler is extending
de Beauvoir’s famous insight that ‘[o]ne is not born, but rather
becomes, a woman’
/P. 10/

*** Criticism
a number of Butler’s critics have expressed their impatience
with what they view as her over-attention to language and her
concomitant neglect of the material and the political, and they accuse
her of quietism (i.e. passivity), nihilism, and ‘killing off’ the subject;
/P. 11/

*** many readers have found potential for political subversion in
theories that consistently affirm the value of destabilizing and deconstructing
the terms by which subjects and identities are constituted... to which Butler repeatedly
returns: What is power? What is subversion? How is it possible
to tell the difference between the two?
/P. 11/

*** Butler’s prose style is not merely a vehicle for politics but effectively
enacts the politics that it describes
/P. 14/

*** If you do experience difficulties
or doubts as you go along, it may be useful to bear in mind the model
Butler suggests for a ‘successful’ reading of Hegel: as readers we should
relinquish our expectations of linear, ‘univocal’ (i.e. singular) meanings,
questioning our own presumptions in order to ‘experience the incessant
movement of the sentence that constitutes its meaning’ (SD: 19).
/P. 15/

** Gender
*** Question the category of woman and women
Rather than starting from the premise that the subject is a
pre-existing metaphysical journeyer, Butler describes it as a *subject-in-process that is constructed in discourse by the acts it performs.*
  /p. 44/
*** Troubles by Gender Trouble
- calling the category of ‘the subject’ into question by arguing
that it is a performative construct; and
- asserting that there are ways of ‘doing’ one’s identity which
will cause even further trouble for those who have a vested
interest in preserving existing oppositions such as male/female,
 /p. 45/
*** Performance vs. performativity
Butler does claim that gender identity is a
sequence of acts (an idea that has existential underpinnings), but she
also argues that there is no pre-existing performer who does those
acts (contrary to performance)... This does not mean that there is no subject,
but that the subject is not exactly where we would expect to find it
– i.e. ‘behind’ or ‘before’ its deeds
 /p. 45/
*** Woman as a term in process
Following de Beauvoir 'One is not born,
but rather becomes, a woman. No biological, psychological, or
economic fate determines the figure that the human female presents
in society; it is civilisation as a whole that produces this creature, inter-
mediate between male and eunuch, which is described as feminine’ Butler expresses 'woman itself is a term in process, a
becoming, a constructing that cannot rightfully be said to originate or to
end... It is, for Beauvoir, never possible finally
to become a woman, as if there were a telos that governs the process of accul-
turation and construction.
(GT: 33)'
/p. 45/

*** Departing from assuming a relation between sex, gender and sexuality
if, for example, one is biologically female, one is
expected to display ‘feminine’ traits and (in a heteronormative world) to
desire men. 
gender is ‘unnatural’, so that
there is no necessary relationship between one’s body and one’s gen-
der.

*** Choosing Gender
 - Butler claims that gender is a ‘choice’ (VSG: 128–9) 
 - ‘choice’ Butler does not mean that a ‘free agent’ or ‘person’ stands outside its gender and simply selects it. 
 - impossible, one is already one’s gender and one’s choice of ‘gender style’ is always limited from the start. 
 - ‘[t]o choose a gender is to interpret received gender norms in a way that organizes them anew. This is not a prescriptive task we must endeavor to do, but one in which we have been endeavoring all along’
/p. 46/

*** Departure from Wittig and Irigaray
placing gender and sex in the context of the discourses by which it is framed
and formed, so that the constructed (as opposed to the ‘natural’) character of both categories will be revealed.
Rejects single or abiding ground from which feminism can or should speak on the ground of being essentialist even for a political startegy.>>displacing categories
Rejects Wittig claim that lesbian is a concept
that is beyond the categories of sex and calls for the destruction of
heterosexuality as a social system on the ground that sex
and gender are discursively constructed and that there is no such
position of implied freedom beyond discourse. Culturally constructed
sexuality cannot be repudiated, so that the subject is left with the
question of how to acknowledge and ‘do’ the construction it is already
in (GT: 31).

*** Gender Genealogies
not historical analysis in the sense she gave in Objects of Desire but in Foucauldian sense ‘genealogy investigates the political stakes
in designating as an origin and cause those identity categories that are
in fact the effects of institutions, practices, discourses, with multiple
and diffused points of origin’ (GT: viii–ix; her emphasis)
*Subject is the effect not the cause, important in performativity*

*** ‘compulsory heterosexuality’
gender is radically independent of sex, ‘a free-floating artifice’

Butler dispenses with the idea that either gender or sex
is an ‘abiding substance’ by arguing that a heterosexual, heterosexist
culture establishes the coherence of those categories in order to
perpetuate and maintain what the feminist poet and critic Adrienne
Rich has called ‘compulsory heterosexuality’

*** ‘Metaphysics of substance’
the sexual heterogeneity that is literally embodied by Herculine constitutes
an implicit critique of what Butler calls ‘the metaphysics of
substance’ and ‘the identitarian categories of sex’

it refers to the pervasive belief that sex
and the body are self-evidently ‘natural’ material entities, whereas we
shall see that, for Butler, sex and gender are ‘phantasmatic’ cultural
constructions which contour and define the body.

*** Gender as a noun
Barbin’s failure to conform to gender binarisms reveals the instability
of those categories, calling into question gender as a substance and the viability of ‘man’ and ‘woman’ as nouns

‘gender is not a noun [but it] proves to be performative, that is, constituting
the identity it is purported to be.

*** Possibility of Gender subversion
To describe gender as a ‘doing’ and a corporeal style might lead you to think of it as
an activity that resembles choosing an outfit from an already-existing
wardrobe of clothes.

*Choosing* is not entirely free, bounded by law, expectations of others, clothes available.

ignoring the expectations and the constraints imposed by your peers, colleagues, etc. by ‘putting on a gender’ can't be done by reinventing your wardrobe or acquiring new one, but by altering what you already have.

*** Structuralist and psychoanalytic accounts of gender
Reading other accounts with a Foucauldian lens:
- a discursive account of the cultural production of gender
- characterizes the law as multiple, proliferating and potentially
self-subverting as opposed to the singular, prohibitive and rigidly
repressive law

*** Reference To Freud
Mourning and Melancholia.
The process of shaping ego as melancholic, by identification with disposition.
Butler refutes innate dispositions of Freud.

*** Melancholic Heterosexuality
- she wants to know how ‘masculine’
and ‘feminine’ dispositions can be traced to an identification, and
where those identifications take place.

- While Freud describes ego formation as a melancholic structure
because the infant is forced to give up its desire for its parents in
response to the taboo against incest, Butler argues that the taboo against
incest is preceded by the taboo against homosexuality.

- `gender identity appears primarily to be the internalization of a prohibition that proves to be formative of identity’

*** Incorporation
- The identification with lost object happens on the surface of the body.
- ‘[G]ender identity would be established through a refusal of loss that encrypts itself in the body . . . incorporation literalizes the
loss on or in the body and so appears as the facticity of the body, the means by which the body comes to bear “sex” as its literal truth’
- Butler accepts that ‘a homosexual for whom heterosexual desire is unthinkable’ will maintain his or her heterosexual desire through the
melancholic incorporation of that desire 
- The body is an imagined structure which is the consequence or the product of desire: ‘the phantasmatic nature of desire reveals the body not as its ground or cause, but as its occasion
and its object’, she writes; ‘The strategy of desire is in part the transfiguration of the desiring body itself’
